version: "3.7"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketsalad-db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
